services:
  db:
    image: postgres
#    restart: always
    ports:
      - "32000:5432"
    expose:
      - "32000"
#    volumes:
#      - ./config/seeders:/var/lib/postgresql/data
#    command:
#      - cp /var/www/html/config/seeders/output.sql:/var/lib/postgresql/data/output.sql
    env_file:
      - ./process.env
    networks:
      - uao_students_wellness_net
    #environment:
    #  - POSTGRES_DB=postgres
    #  - POSTGRES_USER=postgres
    #  - POSTGRES_PASSWORD=postgres
    container_name: db
#    command: bash -c " psql -h 192.168.100.2 -p 32000 -U postgres -d wellness_uao -a -f ./config/seeders/output.sql"

  auth_micro:
    build: ./auth/.
    image: davidventep/auth_micro
    container_name: auth_micro
    command: npm start
    ports:
      - "3003:3003"
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./process.env
    volumes:
      - ./config:/var/www/html/config
    networks:
      - uao_students_wellness_net

  users_micro:
    build: ./users/.
    image: davidventep/users_micro
    container_name: users_micro
    command: npm start
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./process.env
    volumes:
      - ./config:/var/www/html/config
    networks:
      - uao_students_wellness_net

  wellness_micro:
    build: ./wellness/.
    image: davidventep/wellness_micro
    container_name: wellness_micro
    command: npm start
    ports:
      - "3002:3002"
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./process.env
    volumes:
      - ./config:/var/www/html/config
    networks:
      - uao_students_wellness_net

  ui_micro:
    build: ./ui/.
    image: davidventep/ui_micro
    container_name: ui_micro
    command: npm start
    ports:
      - "3000:3000"
    links:
      - db
    depends_on:
      - db
      - auth_micro
      - users_micro
      - wellness_micro
    networks:
      - uao_students_wellness_net

networks:
  uao_students_wellness_net:
